### ISSUE TITLE
Handle app.json file

### ISSUE THREAD

**Issue by jimmypoulsen** [pmbanugo/heroku-review-app-actions#4] opened 2022-04-29 08:03 UTC
When trying to deploy I receive a `KeyError: key not found: "SOME_ARBITRARY_CONFIG_VAR_HERE"` in my build log. I guess this is because you don't handle the app.json file? In our project we have a lot of config variables that our application needs.

Can you think of a way to extract the config variables from the app.json file or do you have a workaround?

**Comment by pmbanugo** [comment] 2022-04-29 08:40
Did you already set this config on Heroku using something like `heroku config:set` or from the UI?

**Comment by amessinger** [comment] 2022-04-29 09:01
That might explain the `Redis::CannotConnectError` I get during the setup of the asset pipeline since the Redis addon requirement is declared in my `app.json` file.

**Comment by pmbanugo** [comment] 2022-04-29 09:23
@amessinger Yeah that's the article I have open as well. I'll check on it later but if you find a solution, feel free to send a PR 🙏🏽

**Comment by pmbanugo** [comment] 2022-04-29 14:51
Hey @jimmypoulsen @amessinger I've made some enhancement. Can you pls try it out using this version `pmbanugo/heroku-review-app-actions@v1.2.0-dev` 

Let me know if it works well for you. The only new thing you need to do is pass a `use-app-json: true` as an input parameter. E.g:

```yaml
on:
  pull_request:
    types: [opened, reopened, closed, synchronize]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test custom actions
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy app action step
        uses: pmbanugo/heroku-review-app-actions@v1.2.0-dev
        # uses: ./actions-composite
        id: deploy
        with:
          api-key: ${{ secrets.HEROKU_API_KEY }}
          pipeline-id: ${{ secrets.HEROKU_PIPELINE_ID }}
          app-name-prefix: getting-started
          region: eu
          # stack: heroku-18
          use-app-json: true
      # Use the output from the `deploy` step
      - name: Get the output url
        run: echo "The URL is ${{ steps.deploy.outputs.url }}"
      - name: Comment on commit
        uses: phulsechinmay/rewritable-pr-comment@v0.2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_IDENTIFIER: "Deploy"
          message: |
            I deployed a review app for you to try out this pull request 👇🏽

            Heroku App: ${{ steps.deploy.outputs.url }}
```

**Comment by pmbanugo** [comment] 2022-04-29 16:28
@guioconnor  Do you have the buildpack defined in the app.json? Does this happen for the first build i.e when the PR was opened/reopened?

**Comment by amessinger** [comment] 2022-04-29 16:37
Hi again, I spend some time trying to improve your action but in the end I'm not knowledgeable enough in how Heroku works so I looked for another solution and ended up using https://github.com/matmar10/heroku-review-app.

Thanks for your initiative and support, have a great rest of the day!

**Comment by guioconnor** [comment] 2022-04-29 16:40
@pmbanugo yes and yes.

**Comment by pmbanugo** [comment] 2022-04-29 18:59
@guioconnor Can you try again using v1.2.0? Set `use-app-json: true`, then close and reopen the PR. I tried it and the buildpacks in the app.json are detected and used. If you still get error you could create an app that I can use to reproduce the error.

**Comment by pmbanugo** [comment] 2022-04-29 19:00
Fixed in https://github.com/pmbanugo/heroku-review-app-actions/pull/8 

Closing the issue because the 1.2.0 release now supports handling app.json.

**Closed by pmbanugo** 2022-04-29 19:00 UTC
Labels: enhancement

**Comment by guioconnor** [comment] 2022-05-03 11:37
@pmbanugo Sorry, I was AFK over the weekend. I tried this morning and something is failing but I haven't looked much into it because I've been exploring the solution proposed by @amessinger

**Comment by jimmypoulsen** [comment] 2022-05-03 13:04
@pmbanugo Works! Thank you so much ⭐

**Comment by guioconnor** [comment] 2022-05-03 15:16
@pmbanugo 

I have returned to this action for some more testing. V1.0 successfully creates the app but —as expected— doesn't use `app.json`. On the other hand 1.2 consistently errors with

```{"id":"conflict","message":"The app and pipeline do not have the same owner. Consider transferring the app to the pipeline's owner before trying again."}```

even though the step is marked as successful.

**Comment by pmbanugo** [comment] 2022-05-03 16:40
@guioconnor  Can you pls create a new issue for that? I think I'll need to pass in the pipeline owner in this case.

**Comment by pmbanugo** [comment] 2022-05-03 16:42
@guioconnor I guess it's related to https://github.com/pmbanugo/heroku-review-app-actions/issues/7 but I would need more info to be able to reproduce the error and provide a better solution. For example, if you have app.json, or if using the API from the team owner, etc.

**Comment by guioconnor** [comment] 2022-05-03 17:39
@pmbanugo done #9
